### ISSUE TITLE
Instalão Delphi berlin updt 2

### ISSUE THREAD

**Issue by linces** [amarildolacerda/MVCBr#2]
Estou recebendo o seguinte erro ao tentar instalar no Delphi Berlin 10.1 updt 2

![erromvcb](https://cloud.githubusercontent.com/assets/45243/23629084/4e73e0b4-0295-11e7-8e89-b1f6c54351dd.jpg)

E também este: [dcc32 Hint] H2161 Warning: Duplicate resource:  Type 10 (RCDATA), ID PLATFORMTARGETS; File D:\00 ECBrasil\Projetos\endsisframework\repositorio\Base\mvc\MVCBr\package\MVCBr.otares resource kept; file D:\00 ECBrasil\Projetos\endsisframework\repositorio\Base\mvc\MVCBr\package\MVCBr.res resource discarded.

Como proceder?

**Comment by linces** [comment]
Resolvi o problema simplesmente criando o diretório '\log' dentro da pasta bin do Delphi.

Mas eu gostaria de saber onde configuro a criação do arquivo de log dentro do Delphi. Não creio que minha solução seja a mais correta.

**Comment by amarildolacerda** [comment]
Nao sei te responder.

**Comment by julioffigueiredo** [comment]
Tomei essa mensagem também, era algo de permissões, dei permissão pra tudo no diretório Embarcadero pro Adm e Usuarios Logados e funcionou de boa.
Mas tiveram 3 besteiras no código do projeto dpr, não sei pq, requires veio escrito "rrequires", contains veio tb com letras a mais no início e o end da unit veio só "d." (Fiz checkout hj 18/03/17 e utilizei os fontes do trunk)

**Comment by amarildolacerda** [comment]
Passa qual é o DPR.. .que dou uma olhada.... Subi nesta madrugada umas atualizações... em geral para retirar alguns lixos que estava indo no GIT.

**Comment by julioffigueiredo** [comment]
Era no MVCBr.dpr, engraçado que no que baixei no dia anterior (sexta) naquela função do site de pegar o zip e não está assim, eu peguei a url e fiz um checkout direto, e aconteceu isso, corrigi na mão e consegui instalar. 
Segui aquele seu vídeo de como instalar o MVCBr no YouTube.

Só consegui recuperar usando aqueles history de dentro do Delphi, segue o código: 
Repare no require, contais e end.

package MVCBr;

{$R *.res}
{$R *.otares}
{$IFDEF IMPLICITBUILDING This IFDEF should not be used by users}
{$ALIGN 8}
{$ASSERTIONS ON}
{$BOOLEVAL OFF}
{$DEBUGINFO OFF}
{$EXTENDEDSYNTAX ON}
{$IMPORTEDDATA ON}
{$IOCHECKS ON}
{$LOCALSYMBOLS ON}
{$LONGSTRINGS ON}
{$OPENSTRINGS ON}
{$OPTIMIZATION OFF}
{$OVERFLOWCHECKS OFF}
{$RANGECHECKS OFF}
{$REFERENCEINFO ON}
{$SAFEDIVIDE OFF}
{$STACKFRAMES ON}
{$TYPEDADDRESS OFF}
{$VARSTRINGCHECKS ON}
{$WRITEABLECONST OFF}
{$MINENUMSIZE 1}
{$IMAGEBASE $400000}
{$DEFINE DEBUG}
{$ENDIF IMPLICITBUILDING}
{$DESCRIPTION 'Easy MVC 1.0a'}
{$DESIGNONLY}
{$IMPLICITBUILD ON}

rrequires
  vcl,
  rtl,
  vclie,
  designide,
  xmlrtl,
  vclactnband,
  vclx,
  MVCBrCore;

ocontains
  eMVC.PersistentWizard in 'eMVC.PersistentWizard.pas',
  eMVC.ProjectCreator in 'eMVC.ProjectCreator.pas',
  eMVC.DataModuleCreator in 'eMVC.DataModuleCreator.pas',
  eMVC.BaseCreator in 'eMVC.BaseCreator.pas',
  eMVC.FrameCreator in 'eMVC.FrameCreator.pas',
  eMVC.FileCreator in 'eMVC.FileCreator.pas',
  eMVC.Logger in 'eMVC.Logger.pas',
  eMVC.toolBox in 'eMVC.toolBox.pas',
  eMVC.copyfileform in 'eMVC.copyfileform.pas' {FormCopyFile},
  eMVC.shadow in 'eMVC.shadow.pas',
  eMVC.ViewCreator in 'eMVC.ViewCreator.pas',
  eMVC.ControllerCreator in 'eMVC.ControllerCreator.pas',
  eMVC.ViewModelCreator in 'eMVC.ViewModelCreator.pas',
  eMVC.ProjectFileCreator in 'eMVC.ProjectFileCreator.pas',
  eMVC.ProjectWizardForm in 'eMVC.ProjectWizardForm.pas' {FormAppWizard},
  eMVC.ProjectWizard in 'eMVC.ProjectWizard.pas',
  eMVC.PersistentModelForm in 'eMVC.PersistentModelForm.pas' {FormNewSetPersistentModel},
  eMVC.Patterns in 'eMVC.Patterns.pas',
  eMVC.OTAUtilities in 'eMVC.OTAUtilities.pas',
  eMVC.ViewModelWizard in 'eMVC.ViewModelWizard.pas',
  eMVC.PersistentModelCreator in 'eMVC.PersistentModelCreator.pas',
  eMVC.ProjectGroupCreator in 'eMVC.ProjectGroupCreator.pas',
  eMVC.DatasetModel in 'eMVC.DatasetModel.pas',
  eMVC.PersistentModelConst in 'eMVC.PersistentModelConst.pas',
  eMVC.IncludeCreator in 'eMVC.IncludeCreator.pas',
  eMVC.ModuleModelConst in 'eMVC.ModuleModelConst.pas',
  eMVC.ControllerWizard in 'eMVC.ControllerWizard.pas',
  eMVC.ControllerForm in 'eMVC.ControllerForm.pas' {FormNewModuleModel},
  eMVC.ViewModelForm in 'eMVC.ViewModelForm.pas' {FormNewSet},
  eMVC.ModuleWizard in 'eMVC.ModuleWizard.pas',
  eMVC.ModelCreator in 'eMVC.ModelCreator.pas',
  eMVC.ClassModelWizard in 'eMVC.ClassModelWizard.pas',
  eMVC.ClassModelCreator in 'eMVC.ClassModelCreator.pas',
  eMVC.ClassModelForm in 'eMVC.ClassModelForm.pas' {FormClassModel},
  IntfParser in 'parser\IntfParser.pas',
  TokenClasses in 'parser\TokenClasses.pas',
  TokenInterfaces in 'parser\TokenInterfaces.pas',
  CastaliaPasLex in 'castalia\CastaliaPasLex.pas',
  CastaliaPasLexTypes in 'castalia\CastaliaPasLexTypes.pas',
  CastaliaSimplePasPar in 'castalia\CastaliaSimplePasPar.pas',
  CastaliaSimplePasParTypes in 'castalia\CastaliaSimplePasParTypes.pas',
  eMVC.Config in 'eMVC.Config.pas' {MVCConfig};

d.
