### ISSUE TITLE
Gerar instalador para o servidor - Serviço

### ISSUE THREAD

**Issue by amarildolacerda** [amarildolacerda/MVCBr#4]
Criar instalador. Interessante usar um motor de uso mais geral (Inno setup - por exemplo)

**Comment by linces** [comment]
Amarildo, nesta parte eu posso contribuir com toda certeza. Se ninguém mais quiser essa tarefa, e se você desejar, tenho uma longa experiência com inno. Só peço que me passe os detalhes de como gostaria que fosse feito.

**Comment by amarildolacerda** [comment]
O Server tem basicamente um EXE (MVCBrServer) na opção StandAlone que deve ser copiado para uma PASTA...
Estamos tentando liberar um aplicativo como Serviço, poderia ser mais uma opção do instalador.
Tem uma opção de instalar o BD de exemplo, pode ser interessante - assim já poderia sair vendo o server funcionando. (isto requer o BD e o metadata dele);

**Comment by amarildolacerda** [comment]
subi um instalador de Servico na pasta .\instalador
